application: restfulie-site
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /
  static_files: static_files/restfulie.html
  upload: static_files/restfulie.html

- url: /
  static_dir: static_files
